### ISSUE TITLE
Incorrect timezone in JSON serialized Date fields

### ISSUE THREAD

**Issue by c2nes** [hashicorp/nomad-java-sdk#6] opened 2018-01-11 20:27 UTC
The ObjectMapper in NomadJson is configured to serialize dates using the SimpleDateFormat `"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"`, but this is only correct when the timezone associated with the Date/DateFormat instance is UTC. When another time zone is in use, the date will be numerically formatted in the given time zone (e.g. EST), but will be suffixed with a literal 'Z' (indicating that it is in UTC).

It looks like the format `"yyyy-MM-dd'T'HH:mm:ss.SSSXX"` would include the offset for the timezone or "Z" for UTC.

Alternatively, calling `setTimeZone(TimeZone.getTimeZone("UTC"))` on the DateFormat appears to force dates to be formatted in UTC in which case either format string would work.

Example code,

```java
Date date = new Date();
System.out.println(date);

SimpleDateFormat oldFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
SimpleDateFormat newFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXX");

System.out.println(oldFormat.format(date));
System.out.println(newFormat.format(date));

oldFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
newFormat.setTimeZone(TimeZone.getTimeZone("UTC"));

System.out.println(oldFormat.format(date));
System.out.println(newFormat.format(date));
```

Example output from my machine (which is set to EST),

```
Thu Jan 11 15:23:07 EST 2018
2018-01-11T15:23:07.234Z
2018-01-11T15:23:07.234-0500
2018-01-11T20:23:07.234Z
2018-01-11T20:23:07.234Z
```

**Comment by cgbaker** [comment] 2018-10-23 20:47
The issue is that there are a few places in Nomad where the system time zone is being used instead of UTC. The solution that I've found is to run the Nomad agent with the environment variable `TZ` set to `UTC`, e.g.: 
```
TZ=UTC nomad agent ... 
```

I've mainly experienced this issue when running the agent on darwin/macOS.

I will go ahead and close this issue, please let me know if this doesn't address the problem.

**Closed by cgbaker** 2018-10-23 20:47 UTC

**Comment by tantra35** [comment] 2019-10-21 11:31
@cgbaker Can you clarify, TZ=UTC, will be enough to set only on worker nodes(on control plane this is not required)?

**Comment by cgbaker** [comment] 2019-10-21 12:55
According to my recollection, it's in the JSON serialization, so it will be necessary on any agent where you are communicating with the HTTP API.
